# Generated by Django 5.2.4 on 2025-07-29 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rent', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('kitchen', models.IntegerField(blank=True, null=True)),
                ('toilet', models.IntegerField()),
                ('parking', models.CharField(choices=[('N', 'Not Available'), ('B', 'Bike'), ('C', 'Car')], default='N', max_length=1)),
                ('preferred', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('FL', 'Family'), ('DNM', 'All')], default='DNM', max_length=3)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/propertied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
