FROM python:3.11-slim

WORKDIR /usr/src/aafnoghar_backend

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/usr/src/aafnoghar_backend

RUN apt-get update && apt-get install -y netcat-openbsd

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/aafnoghar_backend/entrypoint.sh
RUN chmod +x /usr/src/aafnoghar_backend/entrypoint.sh

COPY . .

ENTRYPOINT ["/usr/src/aafnoghar_backend/entrypoint.sh"]