services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  
  web:
    build: ./aafnoghar_backend
    command: gunicorn aafnoghar_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      # Fix the volume mapping
      - ./aafnoghar_backend/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - daphne
  
  daphne:
    build: ./aafnoghar_backend
    command: daphne --bind 0.0.0.0 -p 8002 aafnoghar_backend.asgi:application
    ports:
      - 8002:8002
    volumes:
      # Add volume mapping for daphne too
      - ./aafnoghar_backend/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=aafnoghar
  
volumes:
  postgres_data: