version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=aafnoghar

  daphne:
    build: ./aafnoghar_backend
    command: daphne --bind 0.0.0.0 -p 8002 aafnoghar_backend.asgi:application
    volumes:
      - ./aafnoghar_backend/:/usr/src/aafnoghar_backend/
    expose:
      - 8002
    env_file:
      - ./.env.dev
    depends_on:
      - db

  web:
    build: ./aafnoghar_backend
    command: gunicorn aafnoghar_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./aafnoghar_backend/:/usr/src/aafnoghar_backend/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
      - daphne

volumes:
  postgres_data: