# Generated by Django 5.2.4 on 2025-08-06 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConverstaionMessage',
            new_name='ConversationMessage',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='modifed_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
